Fix `ClassUtil.externalClassVersion` returning null for preview versions
Due to that `checkVersionNumbers` previously said something like:
> UnsupportedOperationException: Unsupported version number [69.0] (maximum 68.65535, Java null)